const types = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCTS_BY_STATE: "GET_PRODUCTS_BY_STATE",
  POST_CUSTOMER_ENQUIRY: "POST_CUSTOMER_ENQUIRY",
  GET_PRODUCTS_CATEGORIES: "GET_PRODUCTS_CATEGORIES",
  GET_STATE_CITY : "GET_STATE_CITY"
};

export default types;
